class InsuranceLocators:
    NAME = "//input[@id='firstname']"
    LAST_NAME = "//input[@id='lastname']"
    DATE = "//input[@id='birthdate']"
    GENDER = "//input[@id='gendermale']"
    ADDRESS = "//input[@id='streetaddress']"
    COUNTRY = "//select[@id='country']"
    ZIP_CODE = "//input[@id='zipcode']"
    CITY = "//input[@id='city']"
    OCCUPATION = "//select[@id='occupation']"
    HOBBY = "//input[@id='other']"
    WEBSITE = "website"
    PICTURE = "picture"
    NEXT1 = "//button[@id='nextenterproductdata']"