[pytest]

python_files = test_*.py
python_classes = Test*
python_functions = test_*

testpaths = tests

addopts =
    -v
    --html=reports/report.html
    --self-contained-html

markers =
    smoke: Smoke Test Cases
    regression: Regression Test Cases
    login: Login Module
    appointment: Appointment Module
    history: History Module
    logout: Logout Module